#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
APP_HOME=$( cd "${0%/*}" >/dev/null 2>&1 && pwd -P )
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
exec "$JAVA_HOME/bin/java" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
